services:
  postgres:
    image: postgres:16.4
    container_name: postgres
    environment:
      POSTGRES_DB: activities
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - fides_network
    ports:
      - "5432:5432"

  login-service:
    build: ./login-service
    container_name: login-service
    depends_on:
      - postgres
    networks:
      - fides_network
    ports:
      - "3000:3000"

  activity-service:
    build: ./activity-service
    container_name: activity-service
    depends_on:
      - postgres
    networks:
      - fides_network
    ports:
      - "4000:4000"

networks:
  fides_network:
    driver: bridge
