version: '3.8'

services:
  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user
      POSTGRES_DB: activities
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Mounting the volume for persistence
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - fides_network

  register-service:
    build: ./register-service
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:user@postgres:5432/activities
    networks:
      - fides_network

  employee-dashboard:
    build: ./employee-dashboard
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:user@postgres:5432/activities
    networks:
      - fides_network

  business-dashboard:
    build: ./business-dashboard
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:user@postgres:5432/activities
    networks:
      - fides_network
 
  matching-service:
    build: ./matching-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - fides_network

volumes:
  postgres_data:  # This volume ensures data persistence for PostgreSQL
    driver: local

networks:
  fides_network:
